# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Online help, cardiac rhythmology institute
  fr: Aide en ligne, institut de rythmologie cardiaque
email: valery@aol.com
description:
  en: Liryc is a research, treatment, innovation and teaching institute, wholly dedicated to the study, diagnosis and treatment of cardiac electrical disorders.
  fr: Liryc est un Institut Hospitalo-Universitaire (IHU) de recherche, de soin, d’innovation et d’enseignement, au service du patient.
index:
  en:
  fr: accueil.html
feed:
  en: /feed.xml
  fr: /flux.xml
baseurl: "/aide-en-ligne" # the subpath of your site, e.g. /blog
url: "https://valeryozenne.github.io/aide-en-ligne/" # the base hostname & protocol for your site
twitter_username: pas de compte twitter
github_username:  valeryozenne

# Build settings
markdown: redcarpet
